package ontology.impl;

import Ontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPersona <br>
 * @version generated on Mon Nov 13 13:46:37 COT 2017 by jcast
 */
public class DefaultPersona extends WrappedIndividualImpl implements Persona {

    public DefaultPersona(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
