package Ontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Nov 13 13:46:37 COT 2017 by jcast
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Cultural
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CULTURAL.<p>
     * 
     */
    public static final OWLClass CLASS_CULTURAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Cultural"));

    /* ***************************************************
     * Class http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Emocional
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EMOCIONAL.<p>
     * 
     */
    public static final OWLClass CLASS_EMOCIONAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Emocional"));

    /* ***************************************************
     * Class http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Intelectual
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INTELECTUAL.<p>
     * 
     */
    public static final OWLClass CLASS_INTELECTUAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Intelectual"));

    /* ***************************************************
     * Class http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Jeisson_Castiblanco
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class JEISSON_CASTIBLANCO.<p>
     * 
     */
    public static final OWLClass CLASS_JEISSON_CASTIBLANCO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Jeisson_Castiblanco"));

    /* ***************************************************
     * Class http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Persona
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONA.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#Persona"));

    /* ***************************************************
     * Class http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#fisica
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FISICA.<p>
     * 
     */
    public static final OWLClass CLASS_FISICA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/jcast/ontologies/2017/10/untitled-ontology-4#fisica"));


}
